name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.md"

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: npm
          cache-dependency-path: |
            .github/workflows/docs.yml
      - run: npx --package prettier@2.5.1 prettier --write "**/*.md"
      - name: Commit changes if any
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m "style: Automatic code formatting" -a
            git push
          fi
